# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xebec}
  s.version = "2.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James A. Rosen"]
  s.date = %q{2011-01-16}
  s.description = %q{Helpers for generating navigation bars}
  s.email = %q{james.a.rosen@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "developer_tasks/doc.rake",
     "developer_tasks/test.rake",
     "doc/example_app/Gemfile",
     "doc/example_app/README.md",
     "doc/example_app/app/controllers/application_controller.rb",
     "doc/example_app/app/controllers/pages_controller.rb",
     "doc/example_app/app/controllers/projects_controller.rb",
     "doc/example_app/app/views/layouts/_site_nav_bar.html.erb",
     "doc/example_app/app/views/layouts/application.html.erb",
     "doc/example_app/app/views/pages/about_us.html.erb",
     "doc/example_app/app/views/pages/faq.html.erb",
     "doc/example_app/app/views/pages/feedback.html.erb",
     "doc/example_app/app/views/pages/home.html.erb",
     "doc/example_app/app/views/pages/privacy_policy.html.erb",
     "doc/example_app/app/views/projects/budget.html.erb",
     "doc/example_app/app/views/projects/edit.html.erb",
     "doc/example_app/app/views/projects/history.html.erb",
     "doc/example_app/app/views/projects/index.html.erb",
     "doc/example_app/app/views/projects/show.html.erb",
     "doc/example_app/config/environment.rb",
     "doc/example_app/config/locales/en.yml",
     "doc/example_app/config/routes.rb",
     "generators/xebec_stylesheet/templates/xebec.css.erb",
     "generators/xebec_stylesheet/xebec_stylesheet_generator.rb",
     "init.rb",
     "lib/xebec.rb",
     "lib/xebec/controller_support.rb",
     "lib/xebec/has_nav_bars.rb",
     "lib/xebec/html5.rb",
     "lib/xebec/nav_bar.rb",
     "lib/xebec/nav_bar_helper.rb",
     "lib/xebec/nav_bar_renderer.rb",
     "lib/xebec/nav_item.rb",
     "lib/xebec/stylesheet_generator.rb",
     "lib/xebec/title_enhanced_nav_bar_renderer.rb",
     "lib/xebec/web_app_theme_renderer.rb",
     "rails/init.rb",
     "tasks/README.md",
     "test/controller_support_test.rb",
     "test/html5_test.rb",
     "test/nav_bar_helper_test.rb",
     "test/nav_bar_renderer_test.rb",
     "test/nav_bar_test.rb",
     "test/test_helper.rb",
     "test/title_enhanced_nav_bar_renderer_test.rb",
     "test/web_app_theme_renderer_test.rb",
     "xebec.gemspec"
  ]
  s.homepage = %q{http://github.com/jamesarosen/xebec}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Xebec Documentation", "--charset", "utf-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Navigation helpers}
  s.test_files = [
    "test/controller_support_test.rb",
     "test/html5_test.rb",
     "test/nav_bar_helper_test.rb",
     "test/nav_bar_renderer_test.rb",
     "test/nav_bar_test.rb",
     "test/test_helper.rb",
     "test/title_enhanced_nav_bar_renderer_test.rb",
     "test/web_app_theme_renderer_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, ["~> 2.10.3"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9.8"])
      s.add_development_dependency(%q<rails>, ["~> 3.0"])
    else
      s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
      s.add_dependency(%q<mocha>, ["~> 0.9.8"])
      s.add_dependency(%q<rails>, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
    s.add_dependency(%q<mocha>, ["~> 0.9.8"])
    s.add_dependency(%q<rails>, ["~> 3.0"])
  end
end

